package org.etsi.sol005.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import lombok.Data;

/**
 * This type represents an \&quot;Individual VNF snapshot\&quot; resource. The \&quot;id\&quot; attributed is used by the NFVO to index and identify the VNF snapshots information resources that are accessible via the NFVO. The identifier is still generated by the VNFM and copied into the present \&quot;VnfSnapshotInfo\&quot; representing the \&quot;Individual VNF snapshot\&quot; resource hold by the NFVO. 
 */

@Data
@JsonInclude(value = JsonInclude.Include.NON_EMPTY, content = JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)

public class VnfSnapshotInfo   {

  private String id;

  private String vnfSnapshotPkgId;

  private VnfSnapshot vnfSnapshot;

  private LccnSubscriptionLinks links;
}

